In [151]:
import numpy as np
import pandas as pd

In [152]:
deliveries=pd.read_csv(r"C:\Users\pooja\OneDrive\Desktop\ipl-rough\deliveries.csv")
deliveries.sample(7)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
123031,980905,1,Kings XI Punjab,Gujarat Lions,17,6,MP Stoinis,P Kumar,WP Saha,4,0,4,NaN,0,NaN,NaN,NaN
56019,501260,1,Kings XI Punjab,Royal Challengers Bangalore,15,6,SE Marsh,CH Gayle,AC Gilchrist,1,0,1,NaN,0,NaN,NaN,NaN
98138,729309,1,Mumbai Indians,Delhi Daredevils,9,1,MEK Hussey,WD Parnell,KA Pollard,0,0,0,NaN,0,NaN,NaN,NaN
162822,1136613,1,Rajasthan Royals,Royal Challengers Bangalore,6,5,AM Rahane,TG Southee,RA Tripathi,0,0,0,NaN,0,NaN,NaN,NaN
176685,1178426,1,Mumbai Indians,Sunrisers Hyderabad,3,1,RG Sharma,B Kumar,Q de Kock,1,0,1,NaN,0,NaN,NaN,NaN
188930,1216532,2,Delhi Capitals,Sunrisers Hyderabad,4,6,SS Iyer,KK Ahmed,S Dhawan,3,0,3,NaN,0,NaN,NaN,NaN
100688,733981,2,Chennai Super Kings,Delhi Daredevils,11,3,SK Raina,LR Shukla,DR Smith,0,0,0,NaN,0,NaN,NaN,NaN

In [153]:
matches=pd.read_csv(r"C:\Users\pooja\OneDrive\Desktop\ipl-rough\matches.csv")
matches.sample(7)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
256,548314,2012,Visakhapatnam,2012-04-09,League,RG Sharma,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Deccan Chargers,Mumbai Indians,Deccan Chargers,bat,Mumbai Indians,wickets,5.0,139.0,20.0,N,NaN,AK Chaudhary,JD Cloete
641,1136566,2018,Jaipur,2018-04-11,League,SV Samson,Sawai Mansingh Stadium,Rajasthan Royals,Delhi Daredevils,Delhi Daredevils,field,Rajasthan Royals,runs,10.0,71.0,6.0,N,D/L,KN Ananthapadmanabhan,Nitin Menon
1012,1359537,2023,Lucknow,2023-05-16,League,MP Stoinis,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Mumbai Indians,Mumbai Indians,field,Lucknow Super Giants,runs,5.0,178.0,20.0,N,NaN,AK Chaudhary,A Nand Kishore
438,734011,2014,Ahmedabad,2014-05-15,League,AM Rahane,"Sardar Patel Stadium, Motera",Rajasthan Royals,Delhi Daredevils,Delhi Daredevils,field,Rajasthan Royals,runs,62.0,202.0,20.0,N,NaN,S Ravi,RJ Tucker
1079,1426294,2024,Delhi,2024-05-07,League,Kuldeep Yadav,"Arun Jaitley Stadium, Delhi",Delhi Capitals,Rajasthan Royals,Rajasthan Royals,field,Delhi Capitals,runs,20.0,222.0,20.0,N,NaN,KN Ananthapadmanabhan,UV Gandhe
801,1216520,2020/21,NaN,2020-10-26,League,CH Gayle,Sharjah Cricket Stadium,Kolkata Knight Riders,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,8.0,150.0,20.0,N,NaN,KN Ananthapadmanabhan,RK Illingworth
79,392204,2009,Durban,2009-05-01,League,Yuvraj Singh,Kingsmead,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,8.0,146.0,20.0,N,NaN,HDPK Dharmasena,S Ravi

In [154]:
def change_name(team_name):
    if team_name in ['Rising Pune Supergiants','Pune Warriors']:
        return 'Rising Pune Supergiant'
    elif team_name=='Royal Challengers Bengaluru':
        return 'Royal Challengers Bangalore'
    elif team_name=='Deccan Chargers':
        return 'Sunrisers Hyderabad'
    elif team_name == 'Delhi Daredevils':
        return 'Delhi Capitals'
    elif team_name== 'Gujarat Lions':
        return 'Gujarat Titans'
    elif team_name == 'Kings XI Punjab':
        return 'Punjab Kings'
    else:
        return team_name

In [155]:
deliveries['batting_team']=deliveries['batting_team'].apply(change_name)
deliveries['bowling_team']=deliveries['bowling_team'].apply(change_name)
matches['team1']=matches['team1'].apply(change_name)
matches['team2']=matches['team2'].apply(change_name)

In [156]:
deliveries=deliveries[(deliveries['batting_team']!='Kochi Tuskers Kerala')&(deliveries['bowling_team']!='Kochi Tuskers Kerala')]
deliveries=deliveries[(deliveries['batting_team']!='Rising Pune Supergiant')&(deliveries['bowling_team']!='Rising Pune Supergiant')]
matches=matches[(matches['team1']!='Kochi Tuskers Kerala')&(matches['team2']!='Kochi Tuskers Kerala')]
matches=matches[(matches['team1']!='Rising Pune Supergiant')&(matches['team2']!='Rising Pune Supergiant')]

In [157]:
# Mapping dictionary for cleaning
venue_mapping = {
    'M Chinnaswamy Stadium, Bengaluru': 'M Chinnaswamy Stadium',
    'M.Chinnaswamy Stadium': 'M Chinnaswamy Stadium',
    'Punjab Cricket Association Stadium, Mohali': 'Punjab Cricket Association IS Bindra Stadium',
    'Punjab Cricket Association IS Bindra Stadium, Mohali': 'Punjab Cricket Association IS Bindra Stadium',
    'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh': 'Punjab Cricket Association IS Bindra Stadium',
    'MA Chidambaram Stadium, Chepauk': 'MA Chidambaram Stadium',
    'MA Chidambaram Stadium, Chepauk, Chennai': 'MA Chidambaram Stadium',
    'Wankhede Stadium, Mumbai': 'Wankhede Stadium',
    'Arun Jaitley Stadium, Delhi': 'Arun Jaitley Stadium',
    'Eden Gardens, Kolkata': 'Eden Gardens',
    'Rajiv Gandhi International Stadium, Uppal': 'Rajiv Gandhi International Stadium',
    'Rajiv Gandhi International Stadium, Uppal, Hyderabad': 'Rajiv Gandhi International Stadium',
    'Dr DY Patil Sports Academy, Mumbai': 'Dr DY Patil Sports Academy',
    'Maharashtra Cricket Association Stadium, Pune': 'Maharashtra Cricket Association Stadium',
    'Himachal Pradesh Cricket Association Stadium, Dharamsala': 'Himachal Pradesh Cricket Association Stadium',
    'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam': 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
    'Brabourne Stadium, Mumbai':'Brabourne Stadium',
    'Sawai Mansingh Stadium, Jaipur':'Sawai Mansingh Stadium',
    'Narendra Modi Stadium, Ahmedabad': 'Narendra Modi Stadium',
    'Zayed Cricket Stadium, Abu Dhabi': 'Zayed Cricket Stadium',
    'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
    'Barsapara Cricket Stadium, Guwahati': 'Barsapara Cricket Stadium',
    'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur': 'Maharaja Yadavindra Singh International Cricket Stadium'
    
    # Add more mappings as necessary
}

# Replace venue names
matches['venue']=matches['venue'].replace(venue_mapping)

In [158]:
venue_to_city = {
    'M Chinnaswamy Stadium': 'Bengaluru',
    'Punjab Cricket Association IS Bindra Stadium': 'Mohali',
    'Feroz Shah Kotla': 'Delhi',
    'Wankhede Stadium': 'Mumbai',
    'Eden Gardens': 'Kolkata',
    'Sawai Mansingh Stadium': 'Jaipur',
    'Rajiv Gandhi International Stadium': 'Hyderabad',
    'MA Chidambaram Stadium': 'Chennai',
    'Dr DY Patil Sports Academy': 'Mumbai',
    'Newlands': 'Cape Town',
    "St George's Park": 'Port Elizabeth',
    'Kingsmead': 'Durban',
    'SuperSport Park': 'Centurion',
    'Buffalo Park': 'East London',
    'New Wanderers Stadium': 'Johannesburg',
    'De Beers Diamond Oval': 'Kimberley',
    'OUTsurance Oval': 'Bloemfontein',
    'Brabourne Stadium': 'Mumbai',
    'Sardar Patel Stadium, Motera': 'Ahmedabad',
    'Barabati Stadium': 'Cuttack',
    'Vidarbha Cricket Association Stadium, Jamtha': 'Nagpur',
    'Himachal Pradesh Cricket Association Stadium': 'Dharamshala',
    'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium': 'Visakhapatnam',
    'Subrata Roy Sahara Stadium': 'Pune',
    'Shaheed Veer Narayan Singh International Stadium': 'Raipur',
    'JSCA International Stadium Complex': 'Ranchi',
    'Sheikh Zayed Stadium': 'Abu Dhabi',
    'Sharjah Cricket Stadium': 'Sharjah',
    'Dubai International Cricket Stadium': 'Dubai',
    'Maharashtra Cricket Association Stadium': 'Pune',
    'Saurashtra Cricket Association Stadium': 'Rajkot',
    'Green Park': 'Kanpur',
    'Holkar Cricket Stadium': 'Indore',
    'Arun Jaitley Stadium': 'Delhi',
    'Narendra Modi Stadium': 'Ahmedabad',
    'Zayed Cricket Stadium': 'Abu Dhabi',
    'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium': 'Lucknow',
    'Barsapara Cricket Stadium': 'Guwahati',
    'Maharaja Yadavindra Singh International Cricket Stadium': 'Chandigarh'
}

matches['city']=matches['venue'].map(venue_to_city)

In [159]:
matches.rename(columns={'id':'match_id'},inplace=True)

In [160]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1006 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   match_id         1006 non-null   int64
 1   season           1006 non-null   object
 2   city             1006 non-null   object
 3   date             1006 non-null   object
 4   match_type       1006 non-null   object
 5   player_of_match  1002 non-null   object
 6   venue            1006 non-null   object
 7   team1            1006 non-null   object
 8   team2            1006 non-null   object
 9   toss_winner      1006 non-null   object
 10  toss_decision    1006 non-null   object
 11  winner           1002 non-null   object
 12  result           1006 non-null   object
 13  result_margin    988 non-null    float64
 14  target_runs      1004 non-null   float64
 15  target_overs     1004 non-null   float64
 16  super_over       1006 non-null   object
 17  method           17 non-null     object
 18  umpire1          1006 non-null   object
 19  umpire2          1006 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 165.0+ KB

In [161]:
matches['date']=pd.to_datetime(matches['date'])
matches['season']=matches['date'].dt.year

### Plan of action

- creating a dataframe containing
    - team1
    - team2
    - season
    - city
    - venue
    - winner
    - target runs of both teams
    - inning

In [164]:
# Step 1: Calculate total runs for each match and inning
inning_runs = deliveries.groupby(['match_id', 'inning'])['total_runs'].sum().reset_index()

# Step 2: Separate into first and second innings
inning1_runs = inning_runs[inning_runs['inning'] == 1][['match_id', 'total_runs']].rename(columns={'total_runs': 'team1_runs'})
inning2_runs = inning_runs[inning_runs['inning'] == 2][['match_id', 'total_runs']].rename(columns={'total_runs': 'team2_runs'})

# Step 3: Merge with matches DataFrame
matches = matches.merge(inning1_runs, on='match_id', how='left')
matches = matches.merge(inning2_runs, on='match_id', how='left')

# Display the updated DataFrame
matches.head()

,match_id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,team1_runs,team2_runs
0,335982,2008,Bengaluru,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,222,82.0
1,335983,2008,Mohali,2008-04-19,League,MEK Hussey,Punjab Cricket Association IS Bindra Stadium,Punjab Kings,Chennai Super Kings,Chennai Super Kings,...,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri,240,207.0
2,335984,2008,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,...,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar,129,132.0
3,335985,2008,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,165,166.0
4,335986,2008,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Sunrisers Hyderabad,Deccan Chargers,...,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan,110,112.0

In [165]:
dashboard_data=matches[['match_id','team1','team2','city','venue','season','team1_runs','team2_runs','winner']]

In [189]:
dashboard_data=dashboard_data.dropna()

In [191]:
dashboard_data.astype()

<class 'pandas.core.frame.DataFrame'>
Index: 1002 entries, 0 to 1005
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   match_id    1002 non-null   int64
 1   team1       1002 non-null   object
 2   team2       1002 non-null   object
 3   city        1002 non-null   object
 4   venue       1002 non-null   object
 5   season      1002 non-null   int32
 6   team1_runs  1002 non-null   int64
 7   team2_runs  1002 non-null   float64
 8   winner      1002 non-null   object
dtypes: float64(1), int32(1), int64(2), object(5)
memory usage: 74.4+ KB

In [195]:
dashboard_data.to_csv('dashboard_ipl.csv',index=False)